### ISSUE TITLE
Enhancement: Add Runtime Data Input for Document Creation

### ISSUE THREAD

**Issue by matthewchivers** [matthewchivers/journal#19]
#### Description
Enhance the `journal` command-line tool to support additional data input at runtime, allowing users to specify topics or tags dynamically when creating a new document. This enhancement will enable the creation of documents with more specific and relevant filenames and metadata.

#### Proposed Functionality
1. **Command Structure:**
   - `journal create --type <document_type> --topic <topic> --tags <tag1,tag2,...>`
   
2. **Implementation Details:**
   - Modify the document creation logic to accept and process additional parameters (`--topic`, `--tags`).
   - Update the templating system to incorporate the new parameters into the document structure and filename.

#### Benefits
- Increased flexibility and specificity in document creation.
- Improved organization and retrieval of documents based on topics and tags.

#### Example Usage
- `journal create --type note --topic "Team Meeting" --tags "projectA, sprint"`

#### Considerations

What if a template requires a topic / tag, but one isn't provided?

e.g. the Path might be. `{{.Year}}/{{.Month}}/{{.Topic}}` - what if topic hasn't been specified? Need to implement some kind of failback (could be a config option).

#### Tasks
- [x] Update CLI interface to handle new parameters.
- [x] Modify document creation logic.
- [x] Update templates to use new data.
- [x] Test new functionality.

#### Related Issues
- [Minimum Viable Product #3](https://github.com/matthewchivers/journal/issues/3)

**Comment by matthewchivers** [comment]
This was tackled for all current values (that we wish to be overridden) with https://github.com/matthewchivers/journal/pull/25https://github.com/matthewchivers/journal/pull/25
